"""Reviews

Revision ID: 058fb2180b9c
Revises: 9ebc7e1a0e98
Create Date: 2025-03-28 15:24:42.080568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058fb2180b9c'
down_revision: Union[str, None] = '9ebc7e1a0e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
