"""Fixed relationship issue

Revision ID: 58f90baf2c2e
Revises: aa7b9e7d33b1
Create Date: 2025-03-25 03:48:16.815390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f90baf2c2e'
down_revision: Union[str, None] = 'aa7b9e7d33b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
