"""Update Restaurants Images ID 2

Revision ID: 9ebc7e1a0e98
Revises: ac975d2b0b4c
Create Date: 2025-03-27 10:59:26.079587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebc7e1a0e98'
down_revision: Union[str, None] = 'ac975d2b0b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('restaurants_image_id_fkey', 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('restaurants_image_id_fkey', 'restaurants', 'restaurant_images', ['image_id'], ['id'])
    # ### end Alembic commands ###
