"""Update Restaurants Images ID

Revision ID: ac975d2b0b4c
Revises: ace1e8fc487f
Create Date: 2025-03-27 10:54:06.298177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac975d2b0b4c'
down_revision: Union[str, None] = 'ace1e8fc487f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'restaurants', 'restaurant_images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'image_id')
    # ### end Alembic commands ###
