"""updated booking model

Revision ID: beac60a8ae5d
Revises: dd20e83a7e60
Create Date: 2025-04-13 18:48:31.897648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beac60a8ae5d'
down_revision: Union[str, None] = 'dd20e83a7e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_username', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('email', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('number_of_guests', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('additional_information', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'additional_information')
    op.drop_column('bookings', 'number_of_guests')
    op.drop_column('bookings', 'event_type')
    op.drop_column('bookings', 'phone_number')
    op.drop_column('bookings', 'email')
    op.drop_column('bookings', 'username')
    # ### end Alembic commands ###
